# Copyright 2020 The Serverless Workflow Specification Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: eventgroups.serverlessworkflow.io
spec:
  group: serverlessworkflow.io
  names:
    kind: EventGroup
    listKind: EventGroupList
    plural: eventgroups
    singular: eventgroup
  scope: Namespaced
  versions:
  - name: v1alpha2
    schema:
      openAPIV3Schema:
        description: EventGroup defines the structure for an event infrastructure
          that can be consumed or produced by a WorkflowDefinition instance
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: EventGroupSpec defines the desired state of EventGroup
            properties:
              events:
                description: List of events deployed for this instance. An event name
                  must be unique in the given namespace.
                items:
                  properties:
                    correlationToken:
                      description: Context attribute name of the CloudEvent which
                        value is to be used for event correlation
                      type: string
                    metadata:
                      additionalProperties:
                        type: string
                      description: Metadata information
                      type: object
                    name:
                      description: Unique event name
                      type: string
                    source:
                      description: CloudEvent source
                      type: string
                    type:
                      description: CloudEvent type
                      type: string
                  required:
                  - name
                  - source
                  - type
                  type: object
                minItems: 1
                type: array
                x-kubernetes-list-type: atomic
            required:
            - events
            type: object
          status:
            description: EventGroupStatus defines the observed state of EventGroup
            properties:
              conditions:
                description: Actual status conditions for the WorkflowDefinition instance
                items:
                  description: Condition describes a general structure for Kubernetes
                    based resources
                  properties:
                    lastTransitionTime:
                      description: LastTransitionTime ...
                      format: date-time
                      type: string
                    message:
                      description: Message ...
                      type: string
                    reason:
                      description: Reason of this condition
                      type: string
                    status:
                      description: Status ...
                      type: string
                    type:
                      description: Type of this condition
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
                x-kubernetes-list-type: atomic
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
