apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: functiongroups.serverlessworkflow.io
spec:
  group: serverlessworkflow.io
  names:
    kind: FunctionGroup
    listKind: FunctionGroupList
    plural: functiongroups
    singular: functiongroup
  scope: Namespaced
  versions:
  - name: v1alpha2
    schema:
      openAPIV3Schema:
        description: ' FunctionGroup defines the structure for a function infrastructure
          that can be called by a WorkflowDefinition instance'
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: FunctionGroupSpec defines the desired state of FunctionGroup
            properties:
              functions:
                description: List of functions deployed for this instance. A function
                  name must be unique in the given namespace.
                items:
                  properties:
                    metadata:
                      additionalProperties:
                        type: string
                      description: Metadata corresponds to the JSON schema field "metadata".
                      type: object
                    name:
                      description: Unique function name
                      type: string
                    resource:
                      description: Function resource (URI)
                      type: string
                    type:
                      description: Function type
                      type: string
                  required:
                  - name
                  - resource
                  type: object
                minItems: 1
                type: array
                x-kubernetes-list-type: atomic
            required:
            - functions
            type: object
          status:
            description: FunctionGroupStatus defines the observed state of FunctionGroup
            properties:
              conditions:
                description: Actual status conditions for the FunctionGroup instance
                items:
                  description: Condition describes a general structure for Kubernetes
                    based resources
                  properties:
                    lastTransitionTime:
                      description: LastTransitionTime ...
                      format: date-time
                      type: string
                    message:
                      description: Message ...
                      type: string
                    reason:
                      description: Reason of this condition
                      type: string
                    status:
                      description: Status ...
                      type: string
                    type:
                      description: Type of this condition
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
