= Workflow Instance

A workflow instance represents a single workflow execution corresponding to the instructions provided by a workflow definition. A workflow instance can be short or long-running. A single workflow instance should be isolated, meaning it should not share state and data with other workflow instances. Workflow instances should be able to communicate with each other via events.

Depending on their workflow definition, workflow instances can be short-lived or can execute for days, weeks, or years.

Each workflow instances should have its unique identifier, which should remain unchanged throughout its execution.

Workflow instances can be started providing some data input. This is described in detail in the xref:spec_details/workflow_data.adoc#data-input[workflow data input] section. Workflow instances can also wait for examples to start their execution, which is the case where a workflow definition contains a xref:spec_details/structure/states/event.adoc[EventState] starting workflow state.

The workflow definition also explicitly defines when a workflow instance should be completed. By default, instances should be completed once there are no active workflow paths (all active paths reach a state containing the default xref:spec_details/structure/related_state_definitions/end_definition.adoc[end definition]), or if the defined xref:spec_details/workflow_timeouts.adoc[`workflowExecTimeout`] time is reached. Other ways, such as using the `terminate` property of the xref:spec_details/structure/related_state_definitions/end_definition.adoc[end definition] to terminate instance execution, or defining an xref:spec_details/workflow_timeouts.adoc[`workflowExecTimeout`] property are also possible.

For long-running workflow-executions, you can utilize the `keepActive` workflow property which provides more control as to when exactly to terminate workflow execution. In cases where a workflow execution should be continued as a new one, the DSL also provides the `continueAs` property which is described in detail in the xref:spec_details/continue_as.adoc[Continuing a new Execution] section.